### ISSUE TITLE
Closed connections and timeouts on PUSH and FETCH

### ISSUE THREAD

**Issue by alexmic** [contribsys/faktory#316] opened 2020-08-06 16:49 UTC
We're experiencing sporadic timeouts and connection resets on both PUSH and FETCH, from Python and Node. 

- Which Faktory package and version? 
  * Pro 1.4.0

- Which Faktory worker package and version? 
  * faktory-worker-node, 3.3.7 and @next
  * faktory-worker-python, 0.4 

- Please include any relevant worker configuration
  * Workers are running on Heroku, Faktory is running on AWS EKS. Traffic thus goes over the internet from worker <-> server. The python worker connects over tcp+tls. The node worker connects to a local stunnel instance which then maintains the connection to the server (same setup as connecting to Redis over TLS for heroku). See the stunnel conf [here](https://github.com/supergreat/heroku-buildpack-stunnel/blob/master/bin/stunnel-conf.sh).  

- Please include any relevant error messages or stacktraces
  * **Node**:
    * Closed connections:
      ```
      Error: Connection closed
        at Connection.onClose (/usr/src/api/node_modules/faktory-worker/lib/connection.js:120:41)
        at /usr/src/api/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19
        at Scope._activate (/usr/src/api/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:51:14)
        at Scope.activate (/usr/src/api/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
        at Socket.bound (/usr/src/api/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20)
        at Socket.emit (events.js:310:20)
        at Socket.EventEmitter.emit (domain.js:482:12)
        at TCP.<anonymous> (net.js:672:12)
      ``` 

    * Resets:
      ```
      at TCP.onStreamRead (internal/stream_base_commons.js:200:27)
      Error: read ECONNRESET
      ```

    * Timeouts:
      ```
      at processTimers (internal/timers.js:475:7)
      at listOnTimeout (internal/timers.js:531:17)
      at Timeout.bound (/app/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
      at ResourceRequest._fireTimeout (/app/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
      TimeoutError: ResourceRequest timed out
      ```
    * stunnel:
      ```
      2020.08.06 04:44:23 LOG5[7333]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
      2020.08.06 04:44:23 LOG3[7333]: No more addresses to connect
      2020.08.06 04:44:23 LOG3[7333]: s_connect: s_poll_wait 174.129.155.89:7419: TIMEOUTconnect exceeded
      ```
  * **Python**:
    ```
    timeout: timed out
    File "inventory/common/faktory/worker.py", line 32, in __call__
      return self._task.func(*args)
    [...snip...]
    File "inventory/worker/client.py", line 28, in queue
      return _client.queue(*args, **kwargs)
    File "inventory/common/faktory/client.py", line 66, in queue
      with faktory.connection() as client:
    File "contextlib.py", line 112, in __enter__
      return next(self.gen)
    File "__init__.py", line 18, in connection
      c.connect()
    File "faktory/client.py", line 21, in connect
      self.is_connected = self.faktory.connect()
    File "faktory/_proto.py", line 64, in connect
      self.socket.connect((self.host, self.port))
    File "ssl.py", line 1172, in connect
      self._real_connect(addr, False)
    File "ssl.py", line 1159, in _real_connect
      super().connect(addr)
    ``` 
  * **Faktory server**:
   Seeing a bunch of `Bad connection: read tcp 10.0.78.94:7419->10.0.70.174:52255: i/o timeout`

- Tests:
  * I performed a load test using Locust, running locally. The job was a simple ping job with a payload of random length which just prints "pong" and then schedules another ping job (to send sending a job within a job). The Faktory server was running in the same k8s cluster as the one above with the following requests/limits: 550m/1500m CPU and 250Mi/300Mi Memory. The worker ran locally on my machine (to simulate the traffic over the internet). Results:
    * 50 concurrent users:
       33 failures (connection reset by peer) out of 11268 pushes (0.3%). Average throughput: 23
    * 150 concurrent users:
       41 failures out of 13665 pushes. Average throughput: 60/s

- Are you using an old version? 
  * No

- Have you checked the changelogs to see if your issue has been fixed in a later version?
  * Yes

**Comment by alexmic** [comment] 2020-08-06 17:28
Also worth noting that the cpu usage and load avg remain consistently low (1-5% and ~0.4 respectively) during the load tests.

**Comment by mperham** [comment] 2020-08-06 21:02
Are the python and JS worker libs using TCP keepalive? It's possible that stunnel or a network hop is closing the socket after some time without use. The Ruby worker [enables keepalive here](https://github.com/contribsys/faktory_worker_ruby/blob/master/lib/faktory/client.rb#L231).

But I believe you are running into a DDOS mitigation: Faktory will [timeout any connection that does not handshake within one second](https://github.com/contribsys/faktory/blob/master/server/server.go#L191). This is so bad actors can't open a connection to Faktory, start the handshake and leave it pending forever. I could increase this timeout but I think it's better to determine why your clients can't handshake within a second sometimes.

**Comment by mperham** [comment] 2020-08-06 21:33
A load test leading to CPU starvation could make it difficult for Faktory to respond within one second, since it burns a fair amount of CPU to hash and check the password. Maybe I should increase this timeout?

**Comment by cdrx** [comment] 2020-08-07 09:09
> Are the python and JS worker libs using TCP keepalive?

There is no TCP keep alive support in the Python worker

**Comment by alexmic** [comment] 2020-08-08 13:00
> Are the python and JS worker libs using TCP keepalive? It's possible that stunnel or a network hop is closing the socket after some time without use. The Ruby worker [enables keepalive here](https://github.com/contribsys/faktory_worker_ruby/blob/master/lib/faktory/client.rb#L231).

I don't think either node, python, or stunnel are configured with keepalive. My current stunnel conf keeps an idle connection for [24 hours](https://github.com/supergreat/heroku-buildpack-stunnel/blob/master/bin/stunnel-conf.sh#L14). This could explain some of the FETCH failures but the worker should then reconnect. 

> 
> But I believe you are running into a DDOS mitigation: Faktory will [timeout any connection that does not handshake within one second](https://github.com/contribsys/faktory/blob/master/server/server.go#L191). This is so bad actors can't open a connection to Faktory, start the handshake and leave it pending forever. I could increase this timeout but I think it's better to determine why your clients can't handshake within a second sometimes.

This sounds like a possible cause for the PUSH failures. I'm not entirely sure why the workers cannot handshake within a second but it's possible given that we're routing over the public internet. We're considering moving to a Heroku private space with VPC peering to keep the traffic internal. Is there anyway we can experiment with a higher timeout? Perhaps a setting?

**Comment by alexmic** [comment] 2020-08-11 11:49
Adding more information -- I removed stunnel to reduce the points of failure but the issue remains with no noticeable improvement. Here's a series of debug events from the node worker (I think these are the same thread of work, there are no correlation ids on these logs so it's hard to tie them together):

```
Aug 11 08:14:18.074
at TCP.<anonymous> (net.js:664:12)
at Socket.EventEmitter.emit (domain.js:498:23)
at Socket.emit (events.js:223:5)
at Connection.onClose (/app/node_modules/faktory-worker/lib/connection.js:120:45)
Error: Connection closed
2020-08-11T05:14:18.074Z lib.faktory ERROR [4906810cxxx]: Failed to queue Faktory job: type=send-notification
2020-08-11T05:14:17.796Z faktory-worker:connection client='HELLO {"hostname":"fb2110ee-fe4e-40e1-9c7d-2cb1ce00e307","v":2,"pwdhash":"a82c8ed7b1xxx"}', server=undefined
2020-08-11T05:14:17.796Z faktory-worker:connection close
2020-08-11T05:14:17.677Z faktory-worker:connection SEND: HELLO {"hostname":"fb2110ee-fe4e-40e1-9c7d-2cb1ce00e307","v":2,"pwdhash":"a82c8ed7b1xxx"}
2020-08-11T05:14:17.637Z faktory-worker:client handshake
2020-08-11T05:14:17.637Z faktory-worker:connection HI {"v":2,"i":5501,"s":"xxx"}
```

**Comment by mperham** [comment] 2020-08-15 21:46
There is no config knob for the handshake timeout today. We could add one but you'd need to build your own custom Faktory to test it. I just increased it to two seconds for future builds.

The only other thing I can think of is sharing the socket between req/resp. For instance, one thread makes a FETCH request, but then other thread gets the same connection to make a PUSH request before getting the FETCH reply. That will get Faktory really confused and lead to a socket error and closed connection. Typically clients should use a connection pool and checkout a connection during the request/reply cycle so there's no sharing during the cycle. For instance, here's the Ruby code for the PUSH request/reply: https://github.com/contribsys/faktory_worker_ruby/blob/master/lib/faktory/client.rb#L148-L153

Do you have a client-side read timeout in your faktory worker?

**Comment by alexmic** [comment] 2020-08-19 14:33
From what I can gather, the node library is using a connection pool, enables keep-alive and has a timeout of 10s https://github.com/jbielick/faktory_worker_node/blob/c5cdc72ca678005b829e79dcc8b4677122e7e844/src/connection.ts#L139. The python library is creating a new connection every time and has a timeout of 30s.

**Comment by alexmic** [comment] 2020-08-24 07:45
Sure, here's the code: https://gist.github.com/alexmic/bdc2144e034269ee5ca235a7fae70af5. I'm using locust.io and I have a worker accepting a `ping` job that just prints `pong`. You can start the Locust UI with `locust -f src/locustfiles/faktory_server.py --host <host under test>`

**Comment by mperham** [comment] 2020-08-26 18:05
Ok, I know nothing about the python ecosystem so you'll need to dumb this down for me. I need to install locust on my MBP and I see this when I follow the install command on locust.io:

```
❯ pip install locust
zsh: /usr/local/bin/pip: bad interpreter: /usr/local/Cellar/python/3.7.2/bin/python3.7: no such file or directory
```

**Comment by mperham** [comment] 2020-08-26 18:13
I reinstalled python from scratch with brew and had to use `pip3`. Making progress.

**Comment by mperham** [comment] 2020-08-26 18:25
I have locust and Faktory Pro running, so I think that's the client/faktory/locust UI processes, I just need the worker process spelled out, I think? Give me the worker code.

**Comment by mperham** [comment] 2020-08-26 18:31
What I have so far:

Faktory Pro: `faktory -e development`
Locust: `locust -f faktory-load-test.py --host localhost` (this is also the client process)
Worker: TBD

**Comment by alexmic** [comment] 2020-08-30 07:11
The node worker does:

```
async function ping (args) {
  logger.info("Pong 🏓: args=%s", args);
}
```

Same for Python.

**Comment by mperham** [comment] 2020-09-03 21:40
@alexmic I'll repeat again: I don't know JS or Python. **Give me the entire, exact JS worker code**, not a snippet.

**Comment by mperham** [comment] 2020-09-08 18:14
I was able to get a basic JS worker running but now I get this error from locust, it is not connecting to Faktory:

```
Error report
 # occurrences      Error                                                                                               
--------------------------------------------------------------------------------------------------------------------------------------------
 15                 faktory queue: "TypeError('inet_pton() argument 2 must be str, not None')"                          
-----
```

**Comment by alexmic** [comment] 2020-09-21 19:37
@mperham Sorry for the late reply, I've been away on holidays! I believe this issue is because there's no port in the Faktory URL given to locust. Try changing `localhost` to `localhost:port`.  

Regarding the workers:

### Python
```
from faktory import Worker

def ping(*args):
    print('pong')

w = Worker(queues=['default'], concurrency=1)
w.register('test', ping)

w.run()
```

You can start with `python worker.py`.

### JavaScript
```
const faktory = require("faktory-worker");

async function ping (args) {
  console.log("pong");
}

faktory.register("ping", ping);
faktory.work();
```

You can start with `node worker.js`.

Both workers require the `FAKTORY_URL` envvar to be set to your Faktory host. We plan to move Faktory within our network (we run on Heroku and will most likely move to a Private Space with VPC peering) so I'll revert back on whether this fixes the issues.

**Comment by mperham** [comment] 2020-09-25 20:02
Still doesn't work. Please give me a working reproduction.

**Closed** 2020-10-26 22:26 UTC
